import type { FilterConfig } from "../filter-engine";

/**
 * Default filter configuration for CodeLens M1.
 * Version must be bumped on any change — it's incorporated into snapshot IDs.
 */
export const DEFAULT_FILTER_CONFIG: FilterConfig = {
  version: "m1.0",

  // §9 rule 2: Ignored directory segments
  ignoredDirectories: [
    ".git",
    "node_modules",
    ".next",
    ".nuxt",
    "dist",
    "build",
    "out",
    "target",
    "vendor",
    "__pycache__",
    ".venv",
    "venv",
    "coverage",
    ".turbo",
    ".cache",
    ".gradle",
    ".idea",
    ".vscode",
    "Pods",
    ".terraform",
    ".yarn",
    "obj",
  ],

  // §9 rule 3: Secret risk (supports * wildcard)
  secretRiskPatterns: [
    ".env",
    ".env.*",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
    "*.keystore",
    "id_rsa",
    "id_rsa.*",
  ],

  // §9 rule 4: Lockfiles (exact filename match)
  lockfiles: [
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "bun.lockb",
    "Cargo.lock",
    "poetry.lock",
    "Pipfile.lock",
    "composer.lock",
    "Gemfile.lock",
    "go.sum",
  ],

  // §9 rule 5: Generated/minified (supports * wildcard)
  generatedOrMinifiedPatterns: [
    "*.min",
    "*.min.css",
    "*.map",
    "*.bundle",
    ".DS_Store",
  ],

  // §9 rule 6: Binary/media extensions (including .svg per spec)
  binaryExtensions: [
    // Images (including SVG per spec §9 rule 6 and §0 locked decisions)
    ".svg",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".avif",
    ".bmp",
    ".tiff",
    ".tif",
    ".ico",
    // Video
    ".mp4",
    ".webm",
    ".mov",
    ".avi",
    ".mkv",
    ".wmv",
    ".flv",
    // Audio
    ".mp3",
    ".wav",
    ".ogg",
    ".aac",
    ".flac",
    ".m4a",
    // Fonts
    ".woff",
    ".woff2",
    ".ttf",
    ".otf",
    ".eot",
    // Archives
    ".zip",
    ".tar",
    ".gz",
    ".bz2",
    ".xz",
    ".7z",
    ".rar",
    ".zst",
    // Documents / data
    ".pdf",
    ".ipynb",
    // Executables / compiled
    ".exe",
    ".dll",
    ".so",
    ".dylib",
    ".wasm",
    ".bin",
    ".o",
    ".a",
    ".lib",
    ".class",
    // Databases
    ".db",
    ".sqlite",
    ".sqlite3",
  ],

  // §9 rule 7: Allowlist — extensions
  allowedExtensions: [
    ".ts",
    ".tsx",
    "",
    ".jsx",
    ".py",
    ".java",
    ".go",
    ".rs",
    ".cpp",
    ".c",
    ".cs",
    ".php",
    ".rb",
    ".sql",
    ".html",
    ".css",
    ".md",
    ".json",
    ".mjs",
    ".cjs",
    ".mts",
    ".cts",
    ".vue",
    ".svelte",
    ".kt",
    ".swift",
    ".scala",
    ".sh",
    ".yml",
    ".yaml",
    ".toml",
    ".ini",
    ".prisma",
    ".graphql",
    ".gql",
    ".proto",
    ".xml",
    ".scss",
    ".less",
    ".mdx",
    ".rst",
    ".txt",
  ],

  // §9 rule 7: Allowlist — specific filenames (supports * wildcard)
  allowedFilenames: [
    "Dockerfile",
    "Dockerfile.*",
    "Makefile",
    "docker-compose.yml",
    "docker-compose.*.yml",
    "Procfile",
    "LICENSE",
    "LICENSE.*",
    "README",
    "README.*",
    "go.mod",
    "Gemfile",
    ".env.example",
    ".env.sample",
    ".env.template",
    ".gitignore",
    ".editorconfig",
    ".eslintrc",
    ".eslintrc.*",
    "eslint.config.*",
    ".prettierrc",
    ".prettierrc.*",
    "prettier.config.*",
    "tsconfig.json",
    "tsconfig.*.json",
    "jsconfig.json",
    "openapi.json",
    "openapi.yaml",
    "openapi.yml",
    "swagger.json",
    "swagger.yaml",
    "swagger.yml",
  ],

  // §9 rule 8: Max single file size
  maxFileSizeBytes: 256 * 1024, // 256 KB

  // §9 global limits
  maxIncludedFiles: 5000,
  maxIncludedBytes: 25 * 1024 * 1024, // 25 MB
};
